stages:
  patch_scenes:
    cmd: python preparedata/extract_patches.py /home/robert/ds-wildfire/raw_data/wildfires-ground-truth/france/vars/N_DFCI_CONTOUR_FEUX_2017_S_083.shp
      /home/robert/ds-wildfire/data/extracted DATE_ECLOS /home/robert/ds-wildfire/data/scenes
      -s 31/T/GJ -s 31/T/GH
    deps:
    - data/scenes/
    - preparedata/extract_patches.py
    - preparedata/patching.py
    - preparedata/patchutils
    - raw_data/wildfires-ground-truth/france/vars/N_DFCI_CONTOUR_FEUX_2017_S_083.shp
    outs:
    - data/extracted/:
        cache: false
