stages:
  patch_scenes:
    cmd: python preparedata/extract_patches.py /home/robert/ds-wildfire/raw_data/wildfires-ground-truth/france/vars/N_DFCI_CONTOUR_FEUX_2017_S_083.shp
      /home/robert/ds-wildfire/data/post_fire_model/extracted DATE_ECLOS /home/robert/ds-wildfire/data/scenes
      -s 31/T/GJ -s 31/T/GH
    deps:
    - data/scenes/
    - preparedata/extract_patches.py
    - preparedata/patching.py
    - preparedata/patchutils
    - raw_data/wildfires-ground-truth/france/vars/N_DFCI_CONTOUR_FEUX_2017_S_083.shp
    outs:
    - data/post_fire_model/extracted/
  merge_bands:
    cmd: python preparedata/merge_bands.py /home/robert/ds-wildfire/raw_data/s2_aws/tiles
      -s 31/T/GH -s 31/T/GJ /home/robert/ds-wildfire/data/scenes
    deps:
    - preparedata/merge_bands.py
    - raw_data/s2_aws/tiles/30
    - raw_data/s2_aws/tiles/31
    outs:
    - data/scenes
  sort_patches:
    cmd: python preparedata/sort_patches.py /home/robert/ds-wildfire/data/post_fire_model/training_patches
      /home/robert/ds-wildfire/excluded.txt /home/robert/ds-wildfire/data/post_fire_model/extracted/patches
      /home/robert/ds-wildfire/data/post_fire_model/extracted/annotations
    deps:
    - data/post_fire_model/extracted/
    - preparedata/sort_patches.py
    outs:
    - data/post_fire_model/training_patches/annotations/
    - data/post_fire_model/training_patches/patches/
  split_data:
    cmd: python preparedata/split.py --root=data/post_fire_model/training_patches/
    deps:
    - data/post_fire_model/training_patches/annotations/
    - data/post_fire_model/training_patches/patches/
    - preparedata/split.py
    outs:
    - data/post_fire_model/training_patches/training_indices.json
  resnetunet:
    cmd: python run_training.py --seed=11 --gpu=1 --save-images=1 --model-name=resnetunet --group=resnetunet_post_fire_model --save-path=data/post_fire_model/
    deps:
    - data/post_fire_model/training_patches/annotations/
    - data/post_fire_model/training_patches/patches/
    - data/post_fire_model/training_patches/training_indices.json
    - run_training.py
    - segmentation/evaluation/
    - segmentation/models/resnetunet/
    - segmentation/networks/resnetunet/
    outs:
    - checkpoint/
    - data/post_fire_model/experiments/resnetunet_post_fire_model/
