stages:
  merge_bands:
    cmd: python -m src.preparedata.merge_bands data/raw_data/tiles -s 29/S/MC -s 29/S/MD
      -s 29/S/NB -s 29/S/NC -s 29/S/ND -s 29/S/PB -s 29/S/PC -s 29/S/PD -s 29/T/ME
      -s 29/T/NE -s 29/T/NF -s 29/T/NG -s 29/T/PE -s 29/T/PF data/processed_data/scenes
    deps:
    - src/preparedata/merge_bands.py
    outs:
    - data/processed_data/scenes/29/S/MC/
    - data/processed_data/scenes/29/S/MD/
    - data/processed_data/scenes/29/S/NB/
    - data/processed_data/scenes/29/S/NC/
    - data/processed_data/scenes/29/S/ND/
    - data/processed_data/scenes/29/S/PB/
    - data/processed_data/scenes/29/S/PC/
    - data/processed_data/scenes/29/S/PD/
    - data/processed_data/scenes/29/T/ME/
    - data/processed_data/scenes/29/T/NE/
    - data/processed_data/scenes/29/T/NF/
    - data/processed_data/scenes/29/T/NG/
    - data/processed_data/scenes/29/T/PE/
    - data/processed_data/scenes/29/T/PF/
  extract_patches:
    cmd: python -m src.preparedata.extract_patches data/raw_data/wildfires-ground-truth/portugal/AArdida2016_ETRS89PTTM06_20190813.shp
      data/processed_data/extracted DHFim data/processed_data/scenes -s 29/S/MC -s
      29/S/MD -s 29/S/NB -s 29/S/NC -s 29/S/ND -s 29/S/PB -s 29/S/PC -s 29/S/PD -s
      29/T/ME -s 29/T/NE -s 29/T/NF -s 29/T/NG -s 29/T/PE -s 29/T/PF
    deps:
    - data/processed_data/scenes/29/S/MC
    - data/processed_data/scenes/29/S/MD
    - data/processed_data/scenes/29/S/NB
    - data/processed_data/scenes/29/S/NC
    - data/processed_data/scenes/29/S/ND
    - data/processed_data/scenes/29/S/PB
    - data/processed_data/scenes/29/S/PC
    - data/processed_data/scenes/29/S/PD
    - data/processed_data/scenes/29/T/ME
    - data/processed_data/scenes/29/T/NE
    - data/processed_data/scenes/29/T/NF
    - data/processed_data/scenes/29/T/NG
    - data/processed_data/scenes/29/T/PE
    - data/processed_data/scenes/29/T/PF
    - data/raw_data/wildfires-ground-truth/portugal/AArdida2016_ETRS89PTTM06_20190813.shp
    - src/preparedata/extract_patches.py
    - src/preparedata/patching.py
    - src/preparedata/patchutils
    outs:
    - data/processed_data/extracted/
  sort_patches:
    cmd: python src/preparedata/sort_patches.py data/processed_data/training_patches
      data/processed_data/extracted/patches data/processed_data/extracted/annotations
    deps:
    - data/processed_data/extracted/
    - src/preparedata/sort_patches.py
    outs:
    - data/processed_data/training_patches/annotations/
    - data/processed_data/training_patches/patches/
  split_data:
    cmd: python -m src.preparedata.split --root=data/processed_data/training_patches/
    deps:
    - data/processed_data/training_patches/annotations/
    - data/processed_data/training_patches/patches/
    - src/preparedata/split.py
    outs:
    - data/processed_data/training_patches/training_indices.json
  resnetunet:
    cmd: python -m src.run_scripts.run_training --seed=11 --gpu=1 --save-images=1
      --baseline=1 --model-name=resnetunet --group=resnetunet --save-path=data/results/
    deps:
    - data/processed_data/training_patches/annotations/
    - data/processed_data/training_patches/patches/
    - data/processed_data/training_patches/training_indices.json
    - src/run_scripts/run_training.py
    - src/segmentation/data/
    - src/segmentation/evaluation/
    - src/segmentation/models/resnetunet/
    - src/segmentation/networks/resnetunet/
  
