stages:
  patch_scenes:
    cmd: python preparedata/extract_patches.py /home/robert/ds-wildfire/raw_data/wildfires-ground-truth/france/vars/N_DFCI_CONTOUR_FEUX_2017_S_083.shp
      /home/robert/ds-wildfire/data/extracted DATE_ECLOS /home/robert/ds-wildfire/data/scenes
      -s 31/T/GJ -s 31/T/GH
    deps:
    - data/scenes/
    - preparedata/extract_patches.py
    - preparedata/patching.py
    - preparedata/patchutils
    - raw_data/wildfires-ground-truth/france/vars/N_DFCI_CONTOUR_FEUX_2017_S_083.shp
    outs:
    - data/extracted/:
        cache: false
  merge_bands:
    cmd: python preparedata/merge_bands.py /home/robert/ds-wildfire/raw_data/s2_aws/tiles
      -s 31/T/GH -s 31/T/GJ /home/robert/ds-wildfire/data/scenes
    deps:
    - preparedata/merge_bands.py
    - raw_data/s2_aws/tiles/30
    - raw_data/s2_aws/tiles/31
    outs:
    - data/scenes:
        cache: false
  sort_patches:
    cmd: python preparedata/sort_patches.py /home/robert/ds-wildfire/data/training_patches
      /home/robert/ds-wildfire/excluded.txt /home/robert/ds-wildfire/data/extracted/patches
      /home/robert/ds-wildfire/data/extracted/anno
    deps:
    - data/extracted/
    - preparedata/sort_patches.py
    outs:
    - data/training_patches/anno/:
        cache: false
    - data/training_patches/patches/:
        cache: false
  split_data:
    cmd: python preparedata/split.py --root=data/training_patches/
    deps:
    - data/training_patches/anno/
    - data/training_patches/patches/
    - preparedata/split.py
    outs:
    - data/training_patches/training_indices.json:
        cache: false
