stages:
  merge_bands:
    cmd: python src/preparedata/merge_bands.py data/raw_data/tiles -s 29/S/MC -s 29/S/MD
      -s 29/S/NB -s 29/S/NC -s 29/S/ND -s 29/S/PB -s 29/S/PC -s 29/S/PD -s 29/T/ME
      -s 29/T/NE -s 29/T/NF -s 29/T/NG -s 29/T/PE -s 29/T/PF data/processed_data/scenes
    deps:
    - src/preparedata/merge_bands.py
